version: '3.8'

services:
  mcub:
    build: .
    container_name: mcub-userbot
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
    environment:
      - MCUB_NO_WEB=0
      - MCUB_PORT=8080
      - MCUB_HOST=0.0.0.0
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8080:8080"
    restart: unless-stopped
    network_mode: host
